import { apiRequest } from "/packages/contracts/api-client.js";
function notify(message) {
  const toast = document.querySelector("#toast");
  if (!toast) return;
  toast.textContent = message;
  toast.classList.add("show");
  window.setTimeout(() => toast.classList.remove("show"), 1800);
}

function setupPaymentFlow(){
  const content=document.getElementById('payment-content');
  if(content){const options=[...content.querySelectorAll('input[name="pay"]')];const detail=document.getElementById('payment-method-detail');const error=document.getElementById('payment-error');const submit=document.getElementById('payment-submit');const draw=method=>{const views={pix:'<div class="payment-method-panel"><span class="feedback-icon success">◇</span><div><strong>Pix</strong><p>Aprovação imediata. O código será gerado após a confirmação.</p></div></div>',credit:'<div class="payment-method-panel payment-fields"><div class="form-group"><label>Número do cartão</label><input class="input" inputmode="numeric" maxlength="19" placeholder="0000 0000 0000 0000"></div><div class="form-row"><div class="form-group"><label>Validade</label><input class="input" maxlength="5" placeholder="MM/AA"></div><div class="form-group"><label>CVV</label><input class="input" inputmode="numeric" maxlength="3" placeholder="000"></div></div></div>',wallet:'<div class="payment-method-panel warning-panel"><span class="feedback-icon warning">!</span><div><strong>Saldo insuficiente</strong><p>Disponível: R$ 32,50 · faltam R$ 18,50.</p><a href="/app/wallet">Adicionar saldo à carteira</a></div></div>'};detail.innerHTML=views[method];error.textContent='';submit.dataset.method=method;submit.dataset.invalid=method==='wallet'?'true':'false';submit.disabled=method==='wallet';submit.textContent='Confirmar pagamento'};options.forEach(option=>option.addEventListener('change',()=>draw(option.value)));draw(options.find(option=>option.checked)?.value||'pix');submit.addEventListener('click',event=>{const method=submit.dataset.method;if(method==='wallet'){event.preventDefault();event.stopImmediatePropagation();error.textContent='O saldo não é suficiente para concluir este pagamento.';return}if(method==='credit'){const fields=[...detail.querySelectorAll('input')];if(fields.some(field=>!field.value.trim())){event.preventDefault();event.stopImmediatePropagation();error.textContent='Preencha todos os dados do cartão.';fields.forEach(field=>field.classList.toggle('invalid',!field.value.trim()))}}},true)}
  const receipt=document.getElementById('receipt-submit');const receiptDetail=document.getElementById('receipt-detail');
  if(receipt&&receiptDetail)receipt.addEventListener('click',()=>{receipt.disabled=true;receipt.innerHTML='<span class="inline-spinner dark"></span> Preparando comprovante...';setTimeout(()=>{receipt.hidden=true;receiptDetail.innerHTML='<div class="receipt-card"><div class="screen-title-row"><strong>Comprovante Pix</strong><span class="badge">Pago</span></div><dl><div><dt>Valor</dt><dd>R$ 51,00</dd></div><div><dt>Transação</dt><dd>PIX-2387-9841-1123</dd></div><div><dt>Status</dt><dd>Protegido em custódia</dd></div></dl><button class="button secondary block" type="button" data-action="download-receipt">Baixar comprovante</button></div>';receiptDetail.querySelector('button').addEventListener('click',()=>notify('Comprovante preparado para download'))},500)})
}
function setupWallet(){
  const content=document.getElementById('wallet-content');if(!content)return;
  const open=document.getElementById('wallet-add-submit');const panel=document.getElementById('wallet-add-panel');const balance=document.getElementById('wallet-balance-value');const filter=document.getElementById('wallet-filter');
  filter?.addEventListener('change',()=>{content.querySelectorAll('[data-kind]').forEach(row=>row.hidden=filter.value!=='all'&&row.dataset.kind!==filter.value)});
  open?.addEventListener('click',()=>{panel.innerHTML='<div class="wallet-add-card"><h2>Adicionar saldo</h2><div class="segmented"><button class="active" type="button">Pix</button><button type="button">Cartão</button></div><div class="form-group"><label>Valor</label><input class="input" id="wallet-add-value" inputmode="decimal" placeholder="R$ 0,00"></div><small class="field-error" id="wallet-add-error"></small><button class="button primary block" id="wallet-confirm-add">Continuar</button></div>';open.hidden=true;const confirm=document.getElementById('wallet-confirm-add');const value=document.getElementById('wallet-add-value');const error=document.getElementById('wallet-add-error');confirm.addEventListener('click',()=>{const amount=Number(value.value.replace(/[^\d,]/g,'').replace(',','.'));if(!amount||amount<=0){error.textContent='Informe um valor válido.';value.classList.add('invalid');return}confirm.disabled=true;confirm.innerHTML='<span class="inline-spinner"></span> Gerando Pix...';setTimeout(()=>{panel.innerHTML=`<div class="wallet-add-card success-panel"><span class="feedback-icon success">✓</span><div><strong>Saldo adicionado</strong><p>R$ ${amount.toFixed(2).replace('.',',')} creditados via Pix.</p></div></div>`;balance.textContent=`R$ ${(32.5+amount).toFixed(2).replace('.',',')}`;notify('Saldo adicionado à carteira')},650)})});
  document.querySelectorAll('[data-action="edit-ad"]').forEach(button=>button.addEventListener('click',()=>notify('Edição do anúncio aberta')));
}
function setupWalletLogisticsExtras(){document.getElementById('wallet-card-add')?.addEventListener('click',()=>{const panel=document.getElementById('wallet-card-panel');panel.innerHTML='<div class="panel"><div class="form-group"><label>Número do cartão</label><input class="input" inputmode="numeric" placeholder="0000 0000 0000 0000"></div><div class="form-row"><div class="form-group"><label>Validade</label><input class="input" placeholder="MM/AA"></div><div class="form-group"><label>CVV</label><input class="input" inputmode="numeric" placeholder="000"></div></div><button class="button primary block" id="wallet-card-save">Salvar cartão</button></div>';document.getElementById('wallet-card-save')?.addEventListener('click',event=>{event.currentTarget.disabled=true;event.currentTarget.textContent='Cartão tokenizado com segurança';notify('Cartão adicionado com segurança')})});document.querySelectorAll('[data-action="remove-card"]').forEach(button=>button.addEventListener('click',()=>{button.closest('.phone-card')?.remove();notify('Cartão removido')}));document.getElementById('dispute-submit')?.addEventListener('click',event=>{const reason=document.getElementById('dispute-reason');const details=document.getElementById('dispute-details');const error=document.getElementById('dispute-error');if(!reason.value||details.value.trim().length<10){error.textContent='Selecione o motivo e descreva o ocorrido com pelo menos 10 caracteres.';return}const content=document.getElementById('dispute-content');event.currentTarget.disabled=true;event.currentTarget.innerHTML='<span class="inline-spinner"></span> Registrando...';setTimeout(()=>{content.innerHTML='<a class="back-link-inline" href="/app/wallet">← Carteira</a><div class="ui-state success-state"><div class="state-icon success">✓</div><span class="eyebrow">Mediação iniciada</span><h1>Disputa registrada</h1><p>O valor permanece protegido enquanto a equipe analisa as evidências.</p><div class="notice">Protocolo #MED-4827 · Retorno estimado em até 2 dias úteis.</div><a class="button primary block" href="/app/wallet">Voltar à carteira</a></div>';notify('Disputa enviada para mediação')},500)});document.getElementById('reschedule-submit')?.addEventListener('click',event=>{event.currentTarget.disabled=true;event.currentTarget.textContent='Entrega reagendada';document.getElementById('reschedule-content')?.insertAdjacentHTML('beforeend','<div class="notice success-notice">Nova janela confirmada. Entregador e vendedor foram notificados.</div>');notify('Entrega reagendada com sucesso')})}

function setupRealPaymentCases(){
  const intentId=sessionStorage.getItem('fc.paymentIntentId');
  const submitCase=async(kind,reason,details,button,error,onSuccess)=>{if(!intentId){error.textContent='Pagamento não identificado. Abra esta opção pelo histórico da carteira.';return}const keyName='fc.paymentCase.'+kind+'.'+intentId;const idempotencyKey=sessionStorage.getItem(keyName)||crypto.randomUUID();sessionStorage.setItem(keyName,idempotencyKey);const original=button.textContent;button.disabled=true;button.innerHTML='<span class="inline-spinner"></span> Enviando...';error.textContent='';try{await apiRequest('/v1/payments/'+intentId+'/'+(kind==='refund'?'refunds':'disputes'),{method:'POST',body:{idempotencyKey,reason,details}});onSuccess()}catch(cause){error.textContent=cause.message||'Não foi possível registrar a solicitação.';button.disabled=false;button.textContent=original}};
  const refundButton=document.getElementById('refund-submit');const refundDetails=document.getElementById('refund-description');const refundError=document.getElementById('refund-error');const refundContent=document.getElementById('refund-content');
  refundButton?.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();const details=refundDetails.value.trim();if(details.length<10){refundError.textContent='Descreva a situação com pelo menos 10 caracteres.';return}void submitCase('refund','customer_request',details,refundButton,refundError,()=>{refundContent.innerHTML='<a class="back-link-inline" href="/app/wallet">← Carteira</a><div class="ui-state success-state"><div class="state-icon success">✓</div><span class="eyebrow">Solicitação recebida</span><h1>Reembolso em análise</h1><p>Registramos sua solicitação e você receberá atualizações no app.</p><div class="notice">Prazo médio: até 7 dias úteis.</div><a class="button primary block" href="/app/wallet">Voltar para a carteira</a></div>';notify('Solicitação enviada com sucesso')})},true);
  const disputeButton=document.getElementById('dispute-submit');const disputeReason=document.getElementById('dispute-reason');const disputeDetails=document.getElementById('dispute-details');const disputeError=document.getElementById('dispute-error');const disputeContent=document.getElementById('dispute-content');
  disputeButton?.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();const reason=disputeReason.value;const details=disputeDetails.value.trim();if(!reason||details.length<10){disputeError.textContent='Selecione o motivo e descreva o ocorrido com pelo menos 10 caracteres.';return}void submitCase('dispute',reason,details,disputeButton,disputeError,()=>{disputeContent.innerHTML='<a class="back-link-inline" href="/app/wallet">← Carteira</a><div class="ui-state success-state"><div class="state-icon success">✓</div><span class="eyebrow">Mediação iniciada</span><h1>Disputa registrada</h1><p>O valor permanece protegido enquanto a equipe analisa as evidências.</p><div class="notice">Retorno estimado em até 2 dias úteis.</div><a class="button primary block" href="/app/wallet">Voltar à carteira</a></div>';notify('Disputa enviada para mediação')})},true)
}

function setupRefundState(){const content=document.getElementById('refund-content');const description=document.getElementById('refund-description');const button=document.getElementById('refund-submit');const error=document.getElementById('refund-error');if(!content||!description||!button||!error)return;button.addEventListener('click',()=>{if(description.value.trim().length<10){error.textContent='Descreva a situação com pelo menos 10 caracteres.';description.classList.add('invalid');description.focus();return}error.textContent='';description.classList.remove('invalid');button.disabled=true;button.innerHTML='<span class="inline-spinner"></span> Enviando...';setTimeout(()=>{content.innerHTML='<a class="back-link-inline" href="/app/wallet">← Carteira</a><div class="ui-state success-state"><div class="state-icon success">✓</div><span class="eyebrow">Solicitação recebida</span><h1>Reembolso em análise</h1><p>Registramos sua solicitação para o pedido <strong>#FC-8F3A2B</strong>.</p><div class="notice">Você receberá atualizações no app. Prazo médio: até 7 dias úteis.</div><a class="button primary block" href="/app/wallet">Voltar para a carteira</a></div>';notify('Solicitação enviada com sucesso')},650)});description.addEventListener('input',()=>{error.textContent='';description.classList.remove('invalid')})}

async function loadPaymentSdk(tokenization){
  const existing=document.querySelector('script[data-payment-provider-sdk]');
  if(existing){if(existing.dataset.ready==='true')return;await new Promise((resolve,reject)=>{existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true})});return}
  await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=tokenization.sdkUrl;script.integrity=tokenization.sdkIntegrity;script.crossOrigin='anonymous';script.dataset.paymentProviderSdk='true';script.addEventListener('load',()=>{script.dataset.ready='true';resolve()},{once:true});script.addEventListener('error',()=>reject(new Error('SDK de pagamento indisponível.')),{once:true});document.head.append(script)})
}

function setupRealPayments(){
  const submit=document.getElementById('payment-submit');const detail=document.getElementById('payment-method-detail');const error=document.getElementById('payment-error');if(!submit||!detail||!error)return;
  submit.addEventListener('click',async event=>{const method=submit.dataset.method;if(method==='wallet')return;event.preventDefault();event.stopImmediatePropagation();const transactionId=sessionStorage.getItem('fc.activeTransactionId');if(!transactionId){error.textContent='Retorne à negociação e selecione o pedido que deseja pagar.';return}
    const original=submit.textContent;submit.disabled=true;submit.innerHTML='<span class="inline-spinner"></span> Preparando pagamento...';error.textContent='';
    try{let paymentMethodToken; if(method==='credit'){const fields=[...detail.querySelectorAll('input')];if(fields.length!==3||fields.some(field=>!field.value.trim()))throw new Error('Preencha todos os dados do cartão.');const session=await apiRequest('/v1/payments/tokenization-sessions',{method:'POST'});await loadPaymentSdk(session.tokenization);const sdk=window.FraldaCyclePaymentProvider;if(!sdk?.tokenizeCard)throw new Error('Tokenização de cartão indisponível.');const tokenized=await sdk.tokenizeCard({clientToken:session.tokenization.clientToken,pan:fields[0].value,expires:fields[1].value,securityCode:fields[2].value});if(typeof tokenized?.token!=='string')throw new Error('Não foi possível tokenizar o cartão.');paymentMethodToken=tokenized.token}
      const keyName='fc.paymentIdempotency.'+transactionId;const idempotencyKey=sessionStorage.getItem(keyName)||crypto.randomUUID();sessionStorage.setItem(keyName,idempotencyKey);const result=await apiRequest('/v1/payments/intents',{method:'POST',body:{transactionId,idempotencyKey,method,paymentMethodToken,deliveryRequested:sessionStorage.getItem('fc.deliveryRequested')==='true'}});sessionStorage.setItem('fc.paymentIntentId',result.intent.id);window.location.assign('/app/payment-success')
    }catch(cause){error.textContent=cause.message||'Não foi possível concluir o pagamento.';submit.disabled=false;submit.textContent=original}
  },true)
}

setupPaymentFlow();
setupRealPayments();
setupWallet();
setupRealPaymentCases();
setupWalletLogisticsExtras();
setupRefundState();
