function notify(message) {
  const toast = document.querySelector("#toast");
  if (!toast) return;
  toast.textContent = message;
  toast.classList.add("show");
  window.setTimeout(() => toast.classList.remove("show"), 1800);
}

function normalizeText(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function blockedChatContent(value){const normalized=normalizeText(value);const digits=value.replace(/\D/g,'');const phonePattern=/(?:\+?55[\s.-]*)?(?:\(?\d{2}\)?[\s.-]*)?(?:9?[\s.-]*\d{4})[\s.-]*\d{4}/;const linkPattern=/(?:https?:\/\/|www\.|\b[a-z0-9-]+\.(?:com|com\.br|net|org|io|app|me|link)\b|bit\.ly|linktr\.ee)/i;const emailPattern=/\b[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}\b/i;const writtenEmail=/(?:arroba|at)\s*(?:gmail|hotmail|outlook|yahoo)|(?:gmail|hotmail|outlook|yahoo)\s*(?:ponto|dot)/;const socialPattern=/\b(?:instagram|insta|facebook|face\s*book|fb|perfil\s+social)\b|@[a-z0-9._]{3,}/i;const qrPattern=/\b(?:qr\s*code|qrcode|codigo\s*qr)\b/i;const numberWords=['zero','um','uma','dois','duas','tres','quatro','cinco','seis','sete','oito','nove'];const writtenDigits=normalized.split(/[^a-z]+/).filter(word=>numberWords.includes(word)).length;if(phonePattern.test(value)||digits.length>=8||writtenDigits>=7)return'Telefones não podem ser compartilhados no chat.';if(emailPattern.test(value)||writtenEmail.test(normalized))return'E-mails não podem ser compartilhados no chat.';if(linkPattern.test(value))return'Links externos não podem ser compartilhados no chat.';if(qrPattern.test(normalized))return'QR Codes não podem ser compartilhados no chat.';if(socialPattern.test(normalized))return'Perfis do Instagram, Facebook ou outras redes não podem ser compartilhados no chat.';return''}
function escapeHtml(value){return value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function setupProtectedChat(){const form=document.getElementById('chat-form');if(!form)return;const input=document.getElementById('msg');const error=document.getElementById('chat-error');form.addEventListener('submit',event=>{event.preventDefault();const message=input.value.trim();if(!message){error.textContent='Digite uma mensagem para enviar.';input.classList.add('invalid');return}const blocked=blockedChatContent(message);if(blocked){error.textContent=blocked+' Mantenha toda a negociação dentro da FraldaCycle.';input.classList.add('invalid');notify('Mensagem bloqueada por segurança');return}error.textContent='';input.classList.remove('invalid');document.getElementById('message-list').insertAdjacentHTML('beforeend',`<div class="message me">${escapeHtml(message)}</div>`);input.value='';notify('Mensagem enviada com segurança')});input.addEventListener('input',()=>{error.textContent='';input.classList.remove('invalid')})}
function setupNegotiation(){
  const form=document.getElementById('proposal-form');
  if(form){const kind=document.getElementById('proposal-kind');const valueGroup=document.getElementById('proposal-value-group');const value=form.querySelector('.proposal-value');const message=document.getElementById('proposal-message');const error=document.getElementById('proposal-error');let selected='Compra';kind.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.kind;kind.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));valueGroup.hidden=selected==='Doação';value.required=selected!=='Doação';if(selected==='Troca')valueGroup.querySelector('label').textContent='Valor complementar (opcional)';else valueGroup.querySelector('label').textContent='Sua proposta';error.textContent=''}));form.addEventListener('submit',event=>{event.preventDefault();const amount=Number(value.value.replace(/[^\d,]/g,'').replace(',','.'));if(selected==='Compra'&&(!Number.isFinite(amount)||amount<=0)){error.textContent='Informe um valor válido para a proposta.';value.classList.add('invalid');return}const blocked=blockedChatContent(message.value.trim());if(blocked){error.textContent=blocked+' Mantenha toda a negociação dentro da FraldaCycle.';message.classList.add('invalid');notify('Proposta bloqueada por segurança');return}value.classList.remove('invalid');message.classList.remove('invalid');error.textContent='';const button=form.querySelector('[type="submit"]');button.disabled=true;button.innerHTML='<span class="inline-spinner"></span> Enviando proposta...';setTimeout(()=>{location.pathname='/app/proposal-received'},650)})}
  const timer=document.getElementById('reservation-timer');
  if(timer){let remaining=Number(timer.dataset.seconds);const draw=()=>{const hours=Math.floor(remaining/3600);const minutes=Math.floor(remaining%3600/60);const seconds=remaining%60;timer.innerHTML=`<strong>${String(hours).padStart(2,'0')}</strong><small>horas</small><strong>${String(minutes).padStart(2,'0')}</strong><small>min</small><strong>${String(seconds).padStart(2,'0')}</strong><small>seg</small>`};draw();const interval=setInterval(()=>{if(!document.body.contains(timer)){clearInterval(interval);return}remaining=Math.max(0,remaining-1);draw();if(remaining===0){clearInterval(interval);location.pathname='/app/reservation-expired'}},1000)}
  const cancelForm=document.getElementById('reservation-cancel-form');cancelForm?.addEventListener('submit',event=>{event.preventDefault();const reason=document.getElementById('reservation-cancel-reason'),confirmation=document.getElementById('reservation-cancel-confirm'),error=document.getElementById('reservation-cancel-error');if(!reason.value||!confirmation.checked){error.textContent='Selecione o motivo e confirme que compreendeu a liberação da reserva.';return}const submit=cancelForm.querySelector('[type="submit"]');submit.disabled=true;submit.innerHTML='<span class="inline-spinner"></span> Cancelando com segurança...';setTimeout(()=>{location.pathname='/app/reservation-cancelled'},650)});
  const stars=[...document.querySelectorAll('.rating-stars button')];if(stars.length){stars.forEach(item=>item.classList.add('selected'));stars[0].parentElement.dataset.rating='5'}stars.forEach((star,index)=>star.addEventListener('click',()=>{stars.forEach((item,itemIndex)=>item.classList.toggle('selected',itemIndex<=index));star.parentElement.dataset.rating=String(index+1);notify(`Avaliação selecionada: ${index+1} de 5`)}));
  const reject=document.getElementById('proposal-reject');reject?.addEventListener('click',()=>{reject.disabled=true;reject.textContent='Recusada';const status=document.getElementById('proposal-decision-status');if(status)status.textContent='Contraproposta recusada. Juliana foi notificada e o registro foi incluído nas evidências.';notify('Contraproposta recusada com registro de evidência.');});
  const evidenceExport=document.getElementById('evidence-export');evidenceExport?.addEventListener('click',()=>{evidenceExport.disabled=true;evidenceExport.textContent='Comprovante preparado';notify('Comprovante de evidências preparado com o protocolo #NEG-2025-0719.');});
}

function setupSafetyActions(){const content=document.getElementById('safety-content');if(!content)return;const form=document.getElementById('safety-form');const reason=document.getElementById('safety-reason');const details=document.getElementById('safety-details');const error=document.getElementById('safety-error');form?.addEventListener('submit',event=>{event.preventDefault();if(!reason.value){error.textContent='Selecione o motivo da denúncia.';reason.classList.add('invalid');reason.focus();return}if(details.value.trim().length<10){error.textContent='Descreva o ocorrido com pelo menos 10 caracteres.';details.classList.add('invalid');details.focus();return}const button=form.querySelector('[type="submit"]');button.disabled=true;button.innerHTML='<span class="inline-spinner"></span> Enviando para análise...';setTimeout(()=>{content.innerHTML='<a class="back-link-inline" href="/app/chat">← Conversa</a><div class="ui-state success-state"><div class="state-icon success">✓</div><span class="eyebrow">Registro protegido</span><h1>Denúncia enviada</h1><p>A equipe de segurança analisará a conversa e as evidências preservadas.</p><div class="notice">Protocolo #SEG-2841 · Você receberá uma atualização nas notificações.</div><a class="button primary block" href="/app/home">Voltar ao início</a></div>';notify('Denúncia enviada para análise')},600)});document.getElementById('block-user')?.addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;button.innerHTML='<span class="inline-spinner"></span> Bloqueando...';setTimeout(()=>{content.innerHTML='<a class="back-link-inline" href="/app/home">← Início</a><div class="ui-state error-state"><div class="state-icon danger">×</div><span class="eyebrow">Usuário bloqueado</span><h1>Conversa indisponível</h1><p>Juliana não poderá enviar novas mensagens ou propostas para você.</p><div class="notice">O conteúdo anterior foi preservado para segurança. Você pode revisar o bloqueio em Configurações e privacidade.</div><a class="button primary block" href="/app/home">Voltar ao início</a></div>';notify('Usuário bloqueado com sucesso')},500)})}
setupProtectedChat();
setupNegotiation();
setupSafetyActions();
