import { apiOrigin, apiRequest } from "/packages/contracts/api-client.js";
function notify(message){const toast=document.querySelector("#toast");if(!toast)return;toast.textContent=message;toast.classList.add("show");window.setTimeout(()=>toast.classList.remove("show"),1800)}
function setupAdmin(){
  const userSearch=document.getElementById('admin-user-search');const userStatus=document.getElementById('admin-user-status');const userTable=document.getElementById('admin-user-table');const userEmpty=document.getElementById('admin-user-empty');
  const filterUsers=()=>{if(!userTable)return;let visible=0;userTable.querySelectorAll('tbody tr').forEach(row=>{const text=row.textContent.toLowerCase();const show=(!userSearch?.value||text.includes(userSearch.value.toLowerCase()))&&(!userStatus?.value||text.includes(userStatus.value.toLowerCase()));row.hidden=!show;if(show)visible++});if(userEmpty)userEmpty.hidden=visible>0};
  userSearch?.addEventListener('input',filterUsers);userStatus?.addEventListener('change',filterUsers);const userProfile=document.getElementById('admin-user-profile');userProfile?.addEventListener('change',()=>{let visible=0;userTable?.querySelectorAll('tbody tr').forEach(row=>{const show=!userProfile.value||row.dataset.profile===userProfile.value;row.hidden=!show;if(show)visible++});if(userEmpty)userEmpty.hidden=visible>0});
  document.getElementById('admin-user-invite')?.addEventListener('click',()=>{const detail=document.getElementById('admin-user-detail');detail.innerHTML='<section class="panel"><div class="section-head"><div><span class="eyebrow">Novo acesso</span><h2>Convidar usuário</h2></div><button class="button ghost small" id="admin-user-invite-close">Fechar</button></div><form id="admin-user-invite-form" class="admin-filters"><input class="input" name="name" required placeholder="Nome completo"><input class="input" name="email" type="email" required placeholder="E-mail"><select class="input" name="profile"><option>Família</option><option>Vendedora</option><option>Entregador</option><option>Administrador</option></select><button class="button primary" type="submit">Enviar convite</button></form></section>';document.getElementById('admin-user-invite-close')?.addEventListener('click',()=>detail.innerHTML='');document.getElementById('admin-user-invite-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('[type="submit"]');const roles={'Família':'customer','Vendedora':'customer','Entregador':'courier','Administrador':'admin'};submit.disabled=true;try{await apiRequest('/v1/admin/invitations',{method:'POST',body:{displayName:form.elements.name.value,email:form.elements.email.value,role:roles[form.elements.profile.value]}});detail.innerHTML='<div class="notice success-notice"><strong>Convite enviado.</strong> O link de uso único expira em 72 horas.</div>';notify('Convite de usuário enviado')}catch(error){submit.disabled=false;const notice=document.createElement('p');notice.className='notice error-notice';notice.textContent=error.message||'Não foi possível enviar o convite.';form.append(notice)}})});
  document.querySelectorAll('[data-admin-user-view]').forEach(button=>button.addEventListener('click',()=>{const row=button.closest('tr');const name=row.querySelector('strong').textContent;const detail=document.getElementById('admin-user-detail');detail.innerHTML=`<section class="panel"><div class="section-head"><div><span class="eyebrow">Perfil administrativo</span><h2>${name}</h2><p>${row.children[1].textContent} · ${row.children[4].textContent}</p></div><button class="button ghost small" id="admin-user-detail-close">Fechar</button></div><div class="stat-grid compact"><article class="stat-card"><small>Verificação</small><strong>${row.children[2].textContent}</strong></article><article class="stat-card"><small>Reputação</small><strong>${row.children[3].textContent}</strong></article><article class="stat-card"><small>Negociações</small><strong>18</strong></article><article class="stat-card"><small>Ocorrências</small><strong>0</strong></article></div></section>`;document.getElementById('admin-user-detail-close')?.addEventListener('click',()=>detail.innerHTML='');detail.scrollIntoView({behavior:'smooth',block:'nearest'})}));
  const operationFilter=document.getElementById('admin-operation-filter');operationFilter?.addEventListener('change',()=>{let visible=0;document.querySelectorAll('#admin-operation-table tbody tr').forEach(row=>{const show=!operationFilter.value&&(visible++,true)||row.dataset.operation===operationFilter.value&&(visible++,true);row.hidden=!show});const empty=document.getElementById('admin-operation-empty');if(empty)empty.hidden=visible>0});
  document.getElementById('admin-operation-refresh')?.addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;button.innerHTML='<span class="inline-spinner dark"></span> Atualizando...';setTimeout(()=>{button.disabled=false;button.textContent='Dados atualizados';notify('Operações sincronizadas agora')},500)});
  document.querySelectorAll('[data-operation-view]').forEach(button=>button.addEventListener('click',()=>{const row=button.closest('tr');const detail=document.getElementById('admin-operation-detail');detail.innerHTML=`<section class="panel"><div class="section-head"><div><span class="eyebrow">${row.children[1].textContent}</span><h2>${row.children[0].textContent}</h2><p>${row.children[2].textContent} · ${row.children[4].textContent}</p></div><button class="button ghost small" id="admin-operation-detail-close">Fechar</button></div><div class="steps"><div class="step active"><div class="step-num">✓</div><div><strong>Registro criado</strong><p>Identidade validada</p></div></div><div class="step active"><div class="step-num">✓</div><div><strong>Condições confirmadas</strong><p>Histórico preservado</p></div></div><div class="step"><div class="step-num">3</div><div><strong>${row.children[3].textContent}</strong><p>Status atual da operação</p></div></div></div><div class="notice">Todos os dados pessoais permanecem protegidos conforme as regras da plataforma.</div></section>`;document.getElementById('admin-operation-detail-close')?.addEventListener('click',()=>detail.innerHTML='');detail.scrollIntoView({behavior:'smooth',block:'nearest'})}));
  document.querySelectorAll('[data-operation-issue]').forEach(button=>button.addEventListener('click',()=>{button.disabled=true;button.textContent='Em análise';notify('Ocorrência encaminhada para análise operacional')}));
  const financeFilter=document.getElementById('admin-finance-filter');financeFilter?.addEventListener('change',()=>{document.querySelectorAll('#admin-finance-table tbody tr').forEach(row=>row.hidden=!!financeFilter.value&&!row.textContent.includes(financeFilter.value))});
  const logisticsFilter=document.getElementById('logistics-status-filter');logisticsFilter?.addEventListener('change',()=>{document.querySelectorAll('#admin-logistics-table tbody tr').forEach(row=>row.hidden=!!logisticsFilter.value&&!row.textContent.includes(logisticsFilter.value))});
  const financeSearch=document.getElementById('finance-search');const filterFinance=()=>{let visible=0;document.querySelectorAll('[data-finance-row]').forEach(row=>{const text=row.textContent.toLowerCase();const show=(!financeSearch?.value||text.includes(financeSearch.value.toLowerCase()))&&(!financeFilter?.value||text.includes(financeFilter.value.toLowerCase()));row.hidden=!show;if(show)visible++});const empty=document.getElementById('finance-empty');if(empty)empty.hidden=visible>0};financeSearch?.addEventListener('input',filterFinance);financeFilter?.addEventListener('change',filterFinance);
  document.getElementById('finance-export')?.addEventListener('click',()=>notify('Extrato financeiro exportado com dados protegidos'));document.getElementById('finance-reconcile')?.addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;button.textContent='Conciliando…';setTimeout(()=>{button.disabled=false;button.textContent='Conciliação concluída';notify('Conciliação financeira concluída sem divergências')},700)});document.querySelectorAll('[data-finance-detail]').forEach(button=>button.addEventListener('click',()=>{const row=button.closest('tr');document.getElementById('finance-detail').innerHTML=`<section class="panel"><div class="section-head"><div><span class="eyebrow">Transação ${row.cells[0].textContent}</span><h2>${row.cells[1].textContent} · ${row.cells[4].textContent}</h2><p>${row.cells[2].textContent} · trilha financeira preservada.</p></div><span class="badge">${row.cells[3].textContent}</span></div><div class="stat-grid compact"><article class="stat-card"><small>Valor</small><strong>${row.cells[4].textContent}</strong></article><article class="stat-card"><small>Split</small><strong>${row.cells[5].textContent}</strong></article><article class="stat-card"><small>Antifraude</small><strong>Aprovado</strong></article><article class="stat-card"><small>Auditoria</small><strong>Íntegra</strong></article></div></section>`;document.getElementById('finance-detail').scrollIntoView({behavior:'smooth',block:'nearest'})}));
  document.getElementById('logistics-refresh')?.addEventListener('click',event=>{event.currentTarget.textContent='Rotas atualizadas';notify('Rotas e previsões atualizadas agora')});document.getElementById('logistics-assign')?.addEventListener('click',()=>notify('Fila de entregadores disponíveis aberta'));document.querySelectorAll('[data-logistics-route]').forEach(pin=>pin.addEventListener('click',()=>{document.querySelectorAll('[data-logistics-route]').forEach(item=>item.classList.remove('active'));pin.classList.add('active');const routes={'FC-8F3A2B':'próximo ao destino · previsão 15:30–16:00','FC-7DE19C':'coleta realizada · previsão 16:00–16:30','FC-3AB87D':'atrasada · requer nova atribuição'};document.getElementById('logistics-route-label').innerHTML=`<strong>#${pin.dataset.logisticsRoute}</strong> · ${routes[pin.dataset.logisticsRoute]}`}));document.querySelectorAll('[data-logistics-issue]').forEach(button=>button.addEventListener('click',()=>{button.textContent='Em análise';button.disabled=true;notify('Ocorrência encaminhada para análise operacional')}));document.querySelectorAll('[data-delivery-view]').forEach(button=>button.addEventListener('click',()=>notify(`Entrega ${button.closest('tr').cells[0].textContent} aberta no rastreamento`)));document.querySelectorAll('[data-delivery-assign]').forEach(button=>button.addEventListener('click',()=>{const row=button.closest('tr');row.cells[1].textContent='Mariana Costa';row.cells[3].innerHTML='<span class="badge">Agendada</span>';button.textContent='Atribuída';button.disabled=true;notify(`${row.cells[0].textContent} atribuída com sucesso`)}));
  document.getElementById('finance-reconcile')?.addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;button.innerHTML='<span class="inline-spinner dark"></span> Conciliando...';setTimeout(()=>{button.textContent='Conciliação concluída';notify('Transações conciliadas com sucesso')},600)});
  document.getElementById('finance-export')?.addEventListener('click',event=>{event.currentTarget.textContent='Extrato preparado';notify('Extrato financeiro preparado para exportação')});
  document.querySelectorAll('[data-review-dispute]').forEach(button=>button.addEventListener('click',()=>{button.textContent='Em análise';button.disabled=true;button.closest('.admin-dispute')?.classList.add('resolved');notify('Disputa encaminhada para mediação')}));
  document.getElementById('logistics-assign')?.addEventListener('click',event=>{event.currentTarget.textContent='Entregador atribuído';notify('Entrega atribuída ao parceiro disponível')});
  document.querySelectorAll('[data-courier-action]').forEach(button=>button.addEventListener('click',()=>{button.textContent=button.textContent.includes('Atribuir')?'Atribuído':'Rota aberta';notify('Operação logística atualizada')}));
  document.getElementById('admin-refresh')?.addEventListener('click',event=>{const button=event.currentTarget;button.disabled=true;button.innerHTML='<span class="inline-spinner dark"></span> Atualizando...';setTimeout(()=>{button.disabled=false;button.textContent='Dados atualizados';notify('Dashboard atualizado agora')},550)});
  const dashboardPeriod=document.getElementById('admin-dashboard-period');dashboardPeriod?.addEventListener('change',()=>{const note=document.getElementById('admin-dashboard-period-note');if(note)note.textContent=`Período de ${dashboardPeriod.value} dias · dados simulados`;notify(`Dashboard ajustado para ${dashboardPeriod.value} dias`)});
  const dashboardStatus=document.getElementById('admin-dashboard-status-filter');dashboardStatus?.addEventListener('change',()=>{let visible=0;document.querySelectorAll('#admin-dashboard-orders-table tbody tr').forEach(row=>{const show=!dashboardStatus.value||row.dataset.status===dashboardStatus.value;row.hidden=!show;if(show)visible++});const empty=document.getElementById('admin-dashboard-orders-empty');if(empty)empty.hidden=visible>0});
  document.querySelectorAll('[data-dashboard-resolve]').forEach(button=>button.addEventListener('click',()=>{const alert=button.closest('[data-dashboard-alert]');button.disabled=true;button.textContent='Revisado';alert?.classList.add('resolved');notify('Alerta revisado e registrado')}));
  document.getElementById('schedule-report')?.addEventListener('click',()=>{const panel=document.getElementById('report-schedule-panel');panel.innerHTML='<section class="panel"><div class="section-head"><div><span class="eyebrow">Novo agendamento</span><h2>Programar envio recorrente</h2></div><button class="button ghost small" id="schedule-close">Fechar</button></div><form id="report-schedule-form"><div class="form-row"><div class="form-group"><label>Frequência</label><select class="input" id="schedule-frequency"><option>Semanal</option><option selected>Mensal</option><option>Trimestral</option></select></div><div class="form-group"><label>Formato</label><select class="input" id="schedule-format"><option>CSV</option><option selected>PDF</option><option>XLSX</option></select></div></div><div class="form-group"><label>E-mail responsável</label><input class="input" id="schedule-email" type="email" value="gestao@fraldacycle.com.br" required></div><small class="field-error" id="schedule-error" role="alert"></small><button class="button primary" type="submit">Confirmar agendamento</button></form></section>';document.getElementById('schedule-close')?.addEventListener('click',()=>panel.innerHTML='');document.getElementById('report-schedule-form')?.addEventListener('submit',scheduleEvent=>{scheduleEvent.preventDefault();const email=document.getElementById('schedule-email');if(!email.checkValidity()){document.getElementById('schedule-error').textContent='Informe um e-mail válido.';return}const frequency=document.getElementById('schedule-frequency').value;const format=document.getElementById('schedule-format').value;panel.innerHTML=`<div class="notice success-notice"><strong>Relatório agendado.</strong> Envio ${frequency.toLowerCase()} em ${format} para ${escapeHtml(email.value)}.</div>`;notify('Agendamento de relatório confirmado')})});
  document.querySelectorAll('[data-report-export]').forEach(button=>button.addEventListener('click',()=>{const format=button.dataset.reportExport;const type=document.getElementById('report-type')?.value||'Executivo';const period=document.getElementById('report-period')?.value||'Mês atual';const status=document.getElementById('report-export-status');button.disabled=true;button.innerHTML=`<span class="inline-spinner dark"></span><strong>Preparando ${format}</strong>`;setTimeout(()=>{const content=`FraldaCycle - Relatório ${type}\nPeríodo: ${period}\nNatureza dos dados: simulados\nFaturamento bruto: R$ 512.980,30\nConversão: 3,82%\nEntrega no prazo: 97,3%\nNPS: 82/100\n`;const mime=format==='CSV'?'text/csv':format==='PDF'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';const blob=new Blob([content],{type:mime});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`fraldacycle-${type.toLowerCase().replace(/\s+/g,'-')}.${format.toLowerCase()}`;link.click();URL.revokeObjectURL(url);button.disabled=false;button.innerHTML=`<span class="feedback-icon success">✓</span><strong>${format} pronto</strong><span>Baixado</span>`;if(status)status.textContent=`${type} · ${period} · ${format} preparado com sucesso.`;notify(`Relatório ${format} exportado`)},550)}));
  const reportTabs=document.querySelectorAll('[data-report-tab]');reportTabs.forEach(tab=>tab.addEventListener('click',()=>{reportTabs.forEach(item=>item.classList.toggle('active',item===tab));document.querySelectorAll('[data-report-section]').forEach(section=>section.hidden=section.dataset.reportSection!==tab.dataset.reportTab)}));document.getElementById('schedule-report-secondary')?.addEventListener('click',()=>document.getElementById('schedule-report')?.click());document.querySelectorAll('[data-report-alert]').forEach(button=>button.addEventListener('click',()=>{button.textContent='Revisado';button.disabled=true;notify('Alerta revisado e registrado')}));document.querySelectorAll('[data-report-open]').forEach(button=>button.addEventListener('click',()=>notify(`Relatório ${button.closest('tr').cells[0].textContent} aberto`)));document.getElementById('report-kpi-detail')?.addEventListener('click',()=>notify('Detalhamento dos indicadores carregado'));
  const alertCount=document.getElementById('alert-count');document.querySelectorAll('[data-resolve-alert]').forEach(button=>button.addEventListener('click',()=>{const alert=button.closest('[data-alert]');button.disabled=true;button.innerHTML='<span class="inline-spinner dark"></span>';setTimeout(()=>{alert.classList.add('resolved');alert.querySelector('p').textContent='Analisado · encaminhamento registrado';button.textContent='Resolvido';const remaining=document.querySelectorAll('[data-alert]:not(.resolved)').length;if(alertCount)alertCount.textContent=remaining?`${remaining} alerta${remaining>1?'s':''} requer${remaining>1?'em':'e'} atenção.`:'Nenhum alerta pendente.';notify('Alerta atualizado')},500)}));
  document.getElementById('refresh-alerts')?.addEventListener('click',()=>notify('Monitoramento atualizado agora'));
  const alertSeverity=document.getElementById('admin-alert-severity');alertSeverity?.addEventListener('change',()=>{document.querySelectorAll('#admin-alert-list [data-severity]').forEach(alert=>alert.hidden=!!alertSeverity.value&&alert.dataset.severity!==alertSeverity.value)});
  document.getElementById('admin-close-sessions')?.addEventListener('click',event=>{document.querySelectorAll('#admin-session-table tbody tr:not([data-current-session])').forEach(row=>{row.children[4].textContent='Encerrada';row.classList.add('resolved')});event.currentTarget.disabled=true;event.currentTarget.textContent='Outras sessões encerradas';notify('Sessões administrativas encerradas')});
  document.getElementById('admin-security-report')?.addEventListener('click',event=>{event.currentTarget.textContent='Evidências revisadas';notify('Evidências de segurança abertas')});
  const rolePermissions={Administrador:['users','ads','operations','finance','reports','settings','audit'],Gestor:['users','ads','operations','reports'],Financeiro:['finance','reports','audit'],Suporte:['users','ads','operations'],Visualizador:['reports']};const roleMeta={Administrador:['12 usuários','Acesso completo com ações críticas protegidas por 2FA.'],Gestor:['28 usuários','Gestão operacional, anúncios e relatórios.'],Financeiro:['15 usuários','Conciliação, estornos, splits e relatórios financeiros.'],Suporte:['22 usuários','Atendimento, usuários, anúncios e operações.'],Visualizador:['48 usuários','Consulta de relatórios sem permissão de alteração.']};const roleSelect=document.getElementById('rbac-role-select');const applyRole=()=>{if(!roleSelect)return;const allowed=rolePermissions[roleSelect.value]||[];document.querySelectorAll('[data-permission]').forEach(input=>input.checked=allowed.includes(input.dataset.permission));const meta=roleMeta[roleSelect.value]||['0 usuários','Papel personalizado.'];document.getElementById('rbac-user-count').textContent=meta[0];document.getElementById('rbac-role-description').textContent=meta[1]};roleSelect?.addEventListener('change',applyRole);document.getElementById('rbac-save')?.addEventListener('click',()=>{document.getElementById('rbac-status').textContent=`Alteração registrada por Marina Lima · ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;notify(`Permissões do papel ${roleSelect.value} atualizadas`)});document.getElementById('rbac-new-role')?.addEventListener('click',()=>{document.getElementById('rbac-role-panel').innerHTML='<section class="panel"><div class="section-head"><div><span class="eyebrow">Novo papel</span><h2>Criar conjunto de acessos</h2></div></div><form id="rbac-new-role-form" class="admin-filters"><input class="input" name="role" required placeholder="Nome do papel"><input class="input" name="description" required placeholder="Descrição e responsabilidade"><button class="button primary" type="submit">Criar papel</button></form></section>';document.getElementById('rbac-new-role-form').addEventListener('submit',event=>{event.preventDefault();const name=new FormData(event.currentTarget).get('role').trim();if(!name)return;rolePermissions[name]=[];roleMeta[name]=['0 usuários','Papel personalizado sem permissões iniciais.'];roleSelect.insertAdjacentHTML('beforeend',`<option>${name}</option>`);roleSelect.value=name;applyRole();event.currentTarget.closest('.panel').remove();notify(`Papel ${name} criado com sucesso`)})});applyRole();
  const admin2fa=document.getElementById('admin-2fa-login');admin2fa?.addEventListener('submit',event=>{event.preventDefault();const panel=document.getElementById('admin-auth-panel');panel.innerHTML='<span class="eyebrow">Segunda etapa</span><h2>Digite o código de segurança</h2><p>Enviamos um código de 6 dígitos para o dispositivo administrativo confiável.</p><form id="admin-2fa-code"><div class="otp" aria-label="Código de autenticação"><input inputmode="numeric" maxlength="1" value="1"><input inputmode="numeric" maxlength="1" value="2"><input inputmode="numeric" maxlength="1" value="3"><input inputmode="numeric" maxlength="1" value="4"><input inputmode="numeric" maxlength="1" value="5"><input inputmode="numeric" maxlength="1" value="6"></div><small class="field-error" id="admin-code-error" role="alert"></small><button class="button primary block" type="submit">Confirmar acesso</button><button class="button text block" type="button" id="admin-code-resend">Reenviar código</button></form><a class="back-link-inline" href="/admin/security">Usar outro método de recuperação</a>';const codeForm=document.getElementById('admin-2fa-code');const inputs=[...codeForm.querySelectorAll('.otp input')];inputs.forEach((input,index)=>input.addEventListener('input',()=>{input.value=input.value.replace(/\D/g,'');if(input.value)inputs[index+1]?.focus()}));document.getElementById('admin-code-resend')?.addEventListener('click',()=>notify('Novo código de segurança enviado'));codeForm.addEventListener('submit',codeEvent=>{codeEvent.preventDefault();const code=inputs.map(input=>input.value).join('');if(!/^\d{6}$/.test(code)){document.getElementById('admin-code-error').textContent='Digite os 6 dígitos do código.';return}panel.innerHTML='<div class="ui-state success-state"><div class="state-icon success">✓</div><span class="eyebrow">Identidade confirmada</span><h2>Acesso administrativo liberado</h2><p>Esta sessão está protegida por autenticação em duas etapas.</p><div class="notice">Chrome · Windows · Belo Horizonte, MG · agora</div><a class="button primary block" href="/admin/dashboard">Abrir painel administrativo</a></div>';notify('Acesso administrativo confirmado com 2FA')})});
}
function setupAdminAds(){const search=document.getElementById('admin-ad-search');const status=document.getElementById('admin-ad-status');if(!search||!status)return;const filter=()=>{let visible=0;document.querySelectorAll('[data-admin-ad]').forEach(row=>{const matchText=row.dataset.search.includes(search.value.trim().toLowerCase());const matchStatus=!status.value||row.dataset.search.includes(status.value.toLowerCase());row.hidden=!(matchText&&matchStatus);if(!row.hidden)visible++});document.getElementById('admin-ad-empty').hidden=visible>0};search.addEventListener('input',filter);status.addEventListener('change',filter);document.querySelectorAll('[data-ad-action]').forEach(button=>button.addEventListener('click',()=>{const row=button.closest('[data-admin-ad]');const id=row.cells[0].textContent;const product=row.cells[1].textContent;if(button.dataset.adAction==='remove'){row.remove();notify(`${id} removido do catálogo`);filter();return}if(button.dataset.adAction==='pause'){row.cells[3].innerHTML='<span class="badge warn">Pausado</span>';notify(`${id} pausado`);return}document.getElementById('admin-ad-review').innerHTML=`<section class="panel"><div class="section-head"><div><span class="eyebrow">Revisão de anúncio</span><h2>${product}</h2><p>${id} · verificação de conteúdo, imagens e regras comerciais.</p></div><span class="badge">Em análise</span></div><div class="dashboard-grid"><div class="phone-list"><article class="phone-card"><span class="status-icon">✓</span><div><h3>Produto fechado</h3><p>Lacre e validade identificados nas imagens.</p></div></article><article class="phone-card"><span class="status-icon">✓</span><div><h3>Categoria e tamanho</h3><p>Marca, tamanho e quantidade coerentes.</p></div></article><article class="phone-card"><span class="status-icon">!</span><div><h3>Preço e descrição</h3><p>Requer confirmação manual antes da publicação.</p></div></article></div><div><label class="form-group">Observação ao anunciante<textarea class="input" rows="4" placeholder="Explique ajustes necessários"></textarea></label><div class="publish-actions action-pair"><button class="button secondary" id="admin-ad-request">Solicitar ajuste</button><button class="button primary" id="admin-ad-approve">Aprovar anúncio</button></div></div></div></section>`;document.getElementById('admin-ad-approve').addEventListener('click',()=>{row.cells[3].innerHTML='<span class="badge">Publicado</span>';document.getElementById('admin-ad-review').innerHTML='';notify(`${id} aprovado e publicado`)});document.getElementById('admin-ad-request').addEventListener('click',()=>notify(`Ajustes solicitados para ${id}`))}));document.getElementById('admin-ad-new')?.addEventListener('click',()=>notify('Cadastro administrativo de produto iniciado'))}
setupAdmin();
setupAdminAds();

const adminEscape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const adminRoleLabels={customer:'Família',courier:'Entregador',moderator:'Moderação',admin:'Administrador'};

async function loadLiveAdminUsers(){
  const table=document.querySelector('#admin-user-table tbody');
  if(!table)return;
  const params=new URLSearchParams({limit:'100'});
  const query=document.getElementById('admin-user-search')?.value.trim();
  if(query)params.set('query',query);
  try{
    const {items}=await apiRequest(`/v1/admin/users?${params}`);
    table.innerHTML=items.map(user=>{
      const name=user.display_name;
      const initials=name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
      const profile=adminRoleLabels[user.role]||user.role;
      const status=user.disabled_at?'Suspenso':'Ativo';
      const verification=user.email_verified_at?'Verificado':'Pendente';
      return `<tr data-profile="${adminEscape(profile)}" data-live-admin-user="${user.id}"><td><div class="admin-user-cell"><span class="avatar">${adminEscape(initials)}</span><div><strong>${adminEscape(name)}</strong><small>${adminEscape(user.email)}</small></div></div></td><td>${adminEscape(profile)}</td><td><span class="status-badge ${user.email_verified_at?'success':'warning'}">${verification}</span></td><td>—</td><td>${status}</td><td><button class="button text" data-live-admin-user-view>Ver perfil</button></td></tr>`;
    }).join('');
    document.documentElement.dataset.adminUsersState='live';
    document.getElementById('admin-user-empty').hidden=items.length>0;
  }catch(error){
    document.documentElement.dataset.adminUsersState=error.status===401?'unauthenticated':error.status===403?'forbidden':'fallback';
  }
}

document.getElementById('admin-user-table')?.addEventListener('click',event=>{
  const button=event.target.closest('[data-live-admin-user-view]');
  if(!button)return;
  const row=button.closest('[data-live-admin-user]');
  const suspended=row.children[4].textContent.trim()==='Suspenso';
  const detail=document.getElementById('admin-user-detail');
  detail.innerHTML=`<section class="panel"><div class="section-head"><div><span class="eyebrow">Conta real</span><h2>${adminEscape(row.querySelector('strong').textContent)}</h2><p>${adminEscape(row.children[1].textContent)} · ${adminEscape(row.children[4].textContent)}</p></div><button class="button ghost small" id="live-user-close">Fechar</button></div><label class="field full"><span>Justificativa da ação</span><textarea class="input" id="live-user-reason" rows="3" placeholder="Registre o motivo com pelo menos 10 caracteres"></textarea></label><small class="field-error" id="live-user-error"></small><button class="button ${suspended?'primary':'secondary'}" id="live-user-status">${suspended?'Reativar conta':'Suspender conta'}</button></section>`;
  document.getElementById('live-user-close').addEventListener('click',()=>detail.innerHTML='');
  document.getElementById('live-user-status').addEventListener('click',async event=>{
    const reason=document.getElementById('live-user-reason').value.trim();
    if(reason.length<10){document.getElementById('live-user-error').textContent='Informe uma justificativa com pelo menos 10 caracteres.';return}
    event.currentTarget.disabled=true;
    try{
      await apiRequest(`/v1/admin/users/${row.dataset.liveAdminUser}/status`,{method:'PATCH',body:{status:suspended?'active':'suspended',reason}});
      detail.innerHTML='';
      await loadLiveAdminUsers();
      notify(suspended?'Conta reativada e auditada':'Conta suspensa, sessões revogadas e ação auditada');
    }catch(error){event.currentTarget.disabled=false;document.getElementById('live-user-error').textContent=error.message}
  });
  detail.scrollIntoView({behavior:'smooth',block:'nearest'});
});
document.getElementById('admin-user-search')?.addEventListener('change',loadLiveAdminUsers);
loadLiveAdminUsers();

async function loadLiveAdminSessions(){
  const body=document.querySelector('#admin-session-table tbody');if(!body)return;
  try{
    const {items}=await apiRequest('/v1/admin/sessions');
    body.innerHTML=items.map(session=>`<tr ${session.current?'data-current-session':''}><td>${adminEscape(session.user_agent||'Dispositivo não identificado')}</td><td>Localização protegida</td><td>${adminEscape(new Date(session.created_at).toLocaleString('pt-BR'))}</td><td><span class="status-badge ${session.current?'success':'neutral'}">${session.current?'Verificada':'Ativa'}</span></td><td>${session.current?'Sessão atual':'Ativa'}</td></tr>`).join('');
    document.documentElement.dataset.adminSessionsState='live';
  }catch(error){document.documentElement.dataset.adminSessionsState=error.status===401?'unauthenticated':error.status===403?'forbidden':'fallback'}
}
document.getElementById('admin-close-sessions')?.addEventListener('click',async event=>{
  event.preventDefault();event.stopImmediatePropagation();const button=event.currentTarget;
  button.disabled=true;button.textContent='Encerrando…';
  try{
    const {revokedCount}=await apiRequest('/v1/admin/sessions/revoke-others',{method:'POST'});
    await loadLiveAdminSessions();button.textContent='Outras sessões encerradas';
    notify(`${revokedCount} sessão${revokedCount===1?'':'ões'} encerrada${revokedCount===1?'':'s'} e auditada${revokedCount===1?'':'s'}`);
  }catch(error){button.disabled=false;button.textContent='Encerrar outras sessões';notify(error.message)}
},true);
loadLiveAdminSessions();

function setupAdminRealtime(){
  const activity=document.querySelector('.activity');
  const note=document.getElementById('admin-dashboard-period-note');
  if(!activity&&!note)return;
  const labels={
    'listing.published':'Anúncio publicado',
    'payment.paid':'Pagamento aprovado',
    'payment.failed':'Pagamento falhou',
    'shipment.assigned':'Entrega atribuída',
    'shipment.delivered':'Entrega confirmada',
    'user.suspended':'Usuário suspenso',
    'user.reactivated':'Usuário reativado',
    'user.role.changed':'Papel de usuário alterado'
  };
  const stream=new EventSource(`${apiOrigin()}/v1/admin/events/stream`,{withCredentials:true});
  stream.onopen=()=>{document.documentElement.dataset.realtimeState='connected';if(note)note.textContent='Conectado · monitoramento em tempo real'};
  stream.onerror=()=>{document.documentElement.dataset.realtimeState='reconnecting';if(note)note.textContent='Reconectando monitoramento…'};
  stream.addEventListener('realtime',event=>{
    const item=JSON.parse(event.data);
    document.documentElement.dataset.lastRealtimeEvent=item.id;
    if(note)note.textContent=`Atualizado agora · ${labels[item.type]||item.type}`;
    if(activity){
      const row=document.createElement('div');row.className='activity-item';row.dataset.realtimeEvent=item.id;
      const source=item.source==='admin'?'AD':item.source==='app'?'AP':item.source==='site'?'SI':'FC';
      row.innerHTML=`<div class="avatar">${source}</div><div><strong>${adminEscape(labels[item.type]||item.type)}</strong><div class="muted">${adminEscape(item.source)} · agora</div></div>`;
      activity.prepend(row);
      [...activity.children].slice(8).forEach(child=>child.remove());
    }
    window.dispatchEvent(new CustomEvent('fraldacycle:realtime',{detail:item}));
  });
  window.addEventListener('pagehide',()=>stream.close(),{once:true});
}
setupAdminRealtime();
